version: "3.3"

services:
  miner:
    build: ../miner
    image: uniquid/dev-miner
    env_file: .env
    ports:
      - 19000:19000
    networks:
      default:
        ipv4_address: 172.18.0.10

  insight-api:
    build: ../insight-api
    image: uniquid/dev-insight-api
    ports:
      - 3001:3001
    networks:
      default:
        ipv4_address: 172.18.0.2
    links:
      - miner

  mqtt:
    build: ../mqtt
    image: uniquid/dev-mqtt
    ports:
      - 1883:1883
      - 1884:1884
    networks:
      default:
        ipv4_address: 172.18.0.3

  tabacchi:
    build: ../tabacchi
    image: uniquid/dev-tabacchi
    env_file: .env
    ports:
      - 8000:8000
    links:
      - miner
    networks:
      default:
        ipv4_address: 172.18.0.4


  registry:
    build: ../registry
    image: uniquid/dev-registry
    ports:
      - 8080:8080
    networks:
      default:
        ipv4_address: 172.18.0.5

  imprinter:
    build: ../imprinter
    image: uniquid/dev-imprinter
    env_file: .env
    ports:
      - 8090:8090
    networks:
      default:
        ipv4_address: 172.18.0.6
    links:
      - miner

  legatus:
    build: ../legatus
    image: uniquid/dev-legatus
    ports:
      - 3000:3000
    networks:
      default:
        ipv4_address: 172.18.0.7

  dashboard:
    build: ../dashboard
    image: uniquid/dev-dashboard
    env_file: .env
    ports:
      - 8081:8081
    networks:
      default:
        ipv4_address: 172.18.0.8

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/16
