version: "3.3"

services:
  miner:
    build: ../miner
    image: uniquid/dev-miner
    ports:
      - 19000:19000
    networks:
      macvlan_net:
          ipv4_address: $MINER_RPC_IP
      dev_net:
          ipv4_address: 172.18.0.100

  insight-api:
    build: ../insight-api
    image: uniquid/dev-insight-api
    ports:
      - 3001:3001
    networks:
      dev_net:
    links:
      - miner

  mqtt:
    build: ../mqtt
    image: uniquid/dev-mqtt
    ports:
      - 1883:1883
      - 1884:1884
    networks:
      dev_net:

  tabacchi:
    build: ../tabacchi
    image: uniquid/dev-tabacchi
    env_file: .env
    ports:
      - 8000:8000
    networks:
      macvlan_net:
          ipv4_address: $TABACCHI_IP
    links:
      - miner

  registry:
    build: ../registry
    image: uniquid/dev-registry
    ports:
      - 8080:8080
    networks:
      dev_net:

  imprinter:
    build: ../imprinter
    image: uniquid/dev-imprinter
    env_file: .env
    ports:
      - 8090:8090
    networks:
      dev_net:
      macvlan_net:
          ipv4_address: $IMPRINTER_IP

  legatus:
    build: ../legatus
    image: uniquid/dev-legatus
    ports:
      - 3000:3000
    networks:
      dev_net:

  dashboard:
    build: ../dashboard
    image: uniquid/dev-dashboard
    env_file: .env
    ports:
      - 8081:8081

# Error response from daemon: network dm-xxx is already using parent interface yyy
# rm /var/lib/docker/network/files/local-kv.db
# restart dockerd
# https://github.com/docker/libnetwork/issues/1743
networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: $MACVLAN_BRIDGE_TO_IF
      gateway: $MACVLAN_GATEWAY_IP
    ipam:
      config:
        - subnet: $MACVLAN_SUBNET_MASK
  dev_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
